version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "Chisanan232"
    labels:
      - "ğŸ” enhancement"
      - "ğŸ¤– github actions"
      - "dependencies"
    commit-message:
      prefix: â¬†