#name: GitHub Action reusable workflow build
name: CI

on:
  push:
    branches:
      - "master"
    paths:
#     CI/CD process of project
      - ".github/tag_and_release/**"
      - ".github/workflows/ci-cd.yaml"
#     Reusable GitHub Action workflows
      - ".github/workflows/rw_**.yaml"
      - "scripts/ci/**.sh"

jobs:
  build_git-tag_and_create_github-release:
#    name: Build git tag and GitHub release if it needs
    uses: ./.github/workflows/rw_build_git-tag_and_create_github-release.yaml
    secrets:
      github_auth_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      project_type: github-action-reusable-workflow
      debug_mode: false


  deploy_as_new_branch:
#    name: Create new git branch by the tagged commit
    needs: build_git-tag_and_create_github-release
    if: ${{ needs.build_git-tag_and_create_github-release.outputs.github-action_reusable_workflow_release_version != 'Pre-Release' }}
    runs-on: ubuntu-latest
    env:
      RELEASE_TYPE: ${{ needs.build_git-tag_and_create_github-release.outputs.github-action_reusable_workflow_release_version }}
      DEBUG_MODE: false
    steps:
      - uses: actions/checkout@v3

      - name: Check it whether get the output of previous one job which has version info or not
        run: bash scripts/ci/check_getting_output.sh

      - name: Create new git branch by the tagged commit
        run: bash ./scripts/ci/deployment_new_version_workflow.sh $DEBUG_MODE

