name: GitHub Action reusable workflow project CI Test

on:
  push:
    branches:
      - "develop**"
      - "master"
    paths:
#     The workflow self.
      - ".github/workflows/test_gh_reusable_workflow.yaml"
#     The shell script only be used by this workflow.
      - "scripts/ci/check_getting_output.sh"
#     The shell scripts or actions this workflow would use.
      - ".github/workflows/rw_build_git-tag_and_create_github-release.yaml"
      - "scripts/ci/build_git-tag_or_create_github-release.sh"
      - "scripts/ci/deployment_new_version_workflow.sh"

  pull_request:
    branches:
      - "develop**"
      - "master"
    paths:
#     The workflow self.
      - ".github/workflows/test_gh_reusable_workflow.yaml"
#     The shell script only be used by this workflow.
      - "scripts/ci/check_getting_output.sh"
#     The shell scripts or actions this workflow would use.
      - ".github/workflows/rw_build_git-tag_and_create_github-release.yaml"
      - "scripts/ci/build_git-tag_or_create_github-release.sh"
      - "scripts/ci/deployment_new_version_workflow.sh"

jobs:
  test_build_git-tag_and_create_github-release:
#    name: Build git tag and GitHub release if it needs
    uses: ./.github/workflows/rw_build_git-tag_and_create_github-release.yaml
    secrets:
      github_auth_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      project_type: github-action-reusable-workflow
      debug_mode: true


  test_deploy_as_new_branch:
#    name: Create new git branch by the tagged commit
    needs: test_build_git-tag_and_create_github-release
    if: ${{ github.event_name == 'push' && 
                needs.test_build_git-tag_and_create_github-release.outputs.github-action_reusable_workflow_release_version != 'Initial' && 
                needs.test_build_git-tag_and_create_github-release.outputs.github-action_reusable_workflow_release_version != 'Pre' }}
    runs-on: ubuntu-latest
    env:
      RELEASE_TYPE: ${{ needs.test_build_git-tag_and_create_github-release.outputs.github-action_reusable_workflow_release_version }}
    steps:
      - uses: actions/checkout@v4

      - name: Check it whether get the output of previous one job which has version info or not
        run: bash scripts/ci/check_getting_output.sh

      - name: Create new git branch by the tagged commit
        run: bash ./scripts/ci/deployment_new_version_workflow.sh 'true'

